<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk"/>
	<Import Project="RevitVersionResolution.props"/>
	<PropertyGroup>
		<BuildTasksDirectoryRoot>$(MSBuildThisFileDirectory)..\tasks\</BuildTasksDirectoryRoot>
		<BuildTasksTFM Condition=" '$(MSBuildRuntimeType)' == 'Core'">net10.0</BuildTasksTFM>
		<BuildTasksTFM Condition=" '$(BuildTasksTFM)' == ''">net48</BuildTasksTFM>
		<BuildTasksDirectory>$(BuildTasksDirectoryRoot)$(BuildTasksTFM)\</BuildTasksDirectory>
		<BuildTasksAssembly>$(BuildTasksDirectory)Toolkit.Revit.Sdk.dll</BuildTasksAssembly>
	</PropertyGroup>
	<UsingTask TaskName="$(MSBuildThisFileName).GenerateAddinManifest" AssemblyFile="$(BuildTasksAssembly)"/>
</Project>
